{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-latexpdf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/latexpdf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/latexpdf/latexpdf_{{ version }}.tar.gz
  sha256: 6fb9bc64df97ab22e6c1e7f286250ebfe06191f9d3b13bfe99090daa2a5937b7

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  requires:
    - r-tinytex
    - perl
  commands:
    - $R -e "library('latexpdf')"  # [not win]
    - $R -e "tinytex::install_tinytex(extra_packages=c('colortbl','multirow'),force=TRUE);latexpdf::as.pdf(head(Theoph))"  # [linux]
    - "\"%R%\" -e \"library('latexpdf')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=latexpdf
  license: GPL-3.0-only
  summary: Converts table-like objects to stand-alone PDF or PNG. Can be used to embed tables and arbitrary content in PDF or Word documents. Provides a low-level R interface for creating 'LaTeX' code, e.g. command() and a high-level interface for creating PDF documents, e.g. as.pdf.data.frame(). Extensive customization
    is available via mid-level functions, e.g. as.tabular(). See also 'package?latexpdf'. Support for PNG is experimental; see 'as.png.data.frame'. Adapted from 'metrumrg' <https://r-forge.r-project.org/R/?group_id=1215>. Requires a compatible installation of 'pdflatex', e.g. <https://miktex.org/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: latexpdf
# Type: Package
# Title: Convert Tables to PDF or PNG
# Version: 0.1.7
# Author: Tim Bergsma
# Maintainer: Tim Bergsma <bergsmat@gmail.com>
# Description: Converts table-like objects to stand-alone PDF or PNG. Can be used to embed tables and arbitrary content in PDF or Word documents. Provides a low-level R interface for creating 'LaTeX' code, e.g. command() and a high-level interface for creating PDF documents, e.g. as.pdf.data.frame(). Extensive customization is available via mid-level functions, e.g. as.tabular(). See also 'package?latexpdf'. Support for PNG is experimental; see 'as.png.data.frame'. Adapted from 'metrumrg' <https://r-forge.r-project.org/R/?group_id=1215>. Requires a compatible installation of 'pdflatex', e.g. <https://miktex.org/>.
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-08-17 18:02:01 UTC; tim.bergsma
# Repository: CRAN
# Date/Publication: 2021-08-17 18:40:02 UTC
